// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoJL.Context;

#nullable disable

namespace ProyectoJL.Migrations
{
    [DbContext(typeof(ProyectJLContext))]
    partial class ProyectJLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoJL.Models.Editorial", b =>
                {
                    b.Property<int>("IDEditorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDEditorial"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LibroIDLibro")
                        .HasColumnType("int");

                    b.Property<string>("NombreEditorial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombrecontacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDEditorial");

                    b.HasIndex("LibroIDLibro");

                    b.ToTable("Editorials");
                });

            modelBuilder.Entity("ProyectoJL.Models.Inventario", b =>
                {
                    b.Property<int>("IdInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInventario"));

                    b.Property<int>("Existencia")
                        .HasColumnType("int");

                    b.Property<int>("IDLibro")
                        .HasColumnType("int");

                    b.Property<int>("IDSucursal")
                        .HasColumnType("int");

                    b.HasKey("IdInventario");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("ProyectoJL.Models.Libro", b =>
                {
                    b.Property<int>("IDLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDLibro"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Foto")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("IDEditorial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InventarioIdInventario")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDLibro");

                    b.HasIndex("InventarioIdInventario");

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("ProyectoJL.Models.Sucursal", b =>
                {
                    b.Property<int>("IDSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDSucursal"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InventarioIdInventario")
                        .HasColumnType("int");

                    b.Property<string>("Nombreencargado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombresucursal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDSucursal");

                    b.HasIndex("InventarioIdInventario");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("ProyectoJL.Models.Editorial", b =>
                {
                    b.HasOne("ProyectoJL.Models.Libro", null)
                        .WithMany("Editorials")
                        .HasForeignKey("LibroIDLibro");
                });

            modelBuilder.Entity("ProyectoJL.Models.Libro", b =>
                {
                    b.HasOne("ProyectoJL.Models.Inventario", null)
                        .WithMany("Libros")
                        .HasForeignKey("InventarioIdInventario");
                });

            modelBuilder.Entity("ProyectoJL.Models.Sucursal", b =>
                {
                    b.HasOne("ProyectoJL.Models.Inventario", null)
                        .WithMany("Sucursals")
                        .HasForeignKey("InventarioIdInventario");
                });

            modelBuilder.Entity("ProyectoJL.Models.Inventario", b =>
                {
                    b.Navigation("Libros");

                    b.Navigation("Sucursals");
                });

            modelBuilder.Entity("ProyectoJL.Models.Libro", b =>
                {
                    b.Navigation("Editorials");
                });
#pragma warning restore 612, 618
        }
    }
}
